cmd:
  type: python-venv
  command:
    default: python -u run.py
  path:
    default: ~/.opereto/operetovenv
item_properties:
- key: test_results_path
  type: text
  value:
  editor: text
  mandatory: true
  direction: input
  help: The path to test results directory
- key: listener_frequency
  type: integer
  value: 10
  editor: number
  mandatory: true
  direction: input
  help: The listener frequency tracking the test results directory for changes
- key: parent_pid
  type: text
  value:
  editor: text
  mandatory: false
  direction: input
  help: Opereto process parent id for test records. If specified, the listener creates new record as direct child processes of that parent process. Otherwise, the listener is the parent process.


timeout: 10000000
type: action